spring:
  profiles.active: development

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

account.service.name: demo-rest-account
exchange-rate.service.name: demo-rest-exchange-rate
logging.file: demo-rest-user.log

---
spring:
  profiles: development

ping.controller.message: User restful service is running in development..

---
spring:
   profiles: test

ping.controller.message: User restful service is running in test.

---
spring:
   profiles: production

ping.controller.message: User restful service is running in production.
