spring:
  profiles.active: development

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
      
---
spring:
  profiles: development

ping.controller.message: Exchange rate restful service is running in development.

---
spring:
   profiles: test

ping.controller.message: Exchange rate restful service is running in test.

---
spring:
   profiles: production

ping.controller.message: Exchange rate restful service is running in production.
