---
# default profile with only a single instance -no need to register as client as no other running

spring:
  profiles: default
server:
  port: 8081
eureka:
  instance:
    hostname: eurekahost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
